### ISSUE TITLE
Paper suggestions

### ISSUE THREAD

**Issue by dimeldo** [snakeztc/NeuralDialogPapers#4]
Papers:
- [DialogWAE: Multimodal Response Generation with Conditional Wasserstein Auto-Encoder](https://arxiv.org/abs/1805.12352) - The most interesting paper currently in my opinion - GAN trained end-to-end without pre-training using MLE or using MLE at all.
- [Towards a Neural Conversation Model with Diversity Net Using Determinantal Point Processes](https://www.aaai.org/ocs/index.php/AAAI/AAAI18/paper/view/17115)
- [Reinforcing Coherence for Sequence to Sequence Model in Dialogue Generation](http://www.bigdatalab.ac.cn/~junxu/publications/IJCAI2018-DialogueGen.pdf)
- [Multi-turn Dialogue Response Generation in an Adversarial Learning Framework](https://arxiv.org/abs/1805.11752) - Combining GAN with MLE in the objective.

Suggestion for this repo:
- I think it can be helpful to organize papers under task-oriented and chit-chat like you do now, but I think it can be better if we'll use Tags rather than categories for describing additional information. This is because a paper can have multiple contributions to it and to describe it under only one roof can be limiting. So maybe a paper could be tagged by "GAN, Hierarchical Structure, Discrete Latents, Transformer, etc..." This way we could break models by components which might help us understand how different components work with each other and also it will allow to search for a particular interest of a model. I don't know how we can implement such a thing but I think I saw something like that on Github before.

**Comment by snakeztc** [comment]
Thanks! I will include these papers. 

Tag is a good idea, not sure how to implement it though. Please let me know if u find a way.
